config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'maps/index'
  end
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
#会員側ルーティング
   scope module: :public do
    root to: "homes#top"
    resources :shops do
     collection do
       get "/favorites" => "shops#favorite"
     end
      resource :favorite_shops, only: [:create, :destroy]
      resource :reviews, only: [:create, :update]
      resources :shop_comments, only: [:create, :destroy]
      resources :maps, only: [:index]
    end
    get "users/my_page" => "users#show"
    get "users/information/edit" => "users#edit"
    patch "users/information" => "users#update"
    put "users/information" => "users#update"
    get "users/shops" =>"users#index"
    get "users/withdraw" => "users#confirm_withdraw"
    patch "users/withdraw" => "users#withdraw"
    get "users/comments" => "users#comments"
    delete "users/comments" => "users#comment_destroy"
    resources :genres, only: [:new, :create, :show]
    get "genre_search" => "searches#genre_search"
    get "search" => "searches#name_search"
    get "rank" => "ranks#rank"
  end
#管理者側ルーティング
  namespace :admin do
    get "" => "homes#top"
    resources :users, :except => :destroy do
      member do
        get "/withdraw" => "users#confirm_withdraw"
        patch "/withdraw" => "users#withdraw"
      end
    end
    resources :genres, only: [:index, :create, :destroy]
    resources :shops, :except => [:create, :destroy]
    resources :shop_comments, only: [:index, :show, :destroy]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :shops
end

app/models/favorite_shop.rb
class FavoriteShop < ApplicationRecord
  belongs_to :user
  belongs_to :shop

  validates_uniqueness_of :shop_id, scope: :user_id
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :shops, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :shop

end

app/models/shop.rb
class Shop < ApplicationRecord
  geocoded_by :location
  after_validation :geocode

  belongs_to :user
  belongs_to :genre
  has_many :favorite_shops, dependent: :destroy
  has_many :shop_comments, dependent: :destroy
  has_many :reviews, dependent: :destroy

  has_one_attached :image

  validates :name, presence: true, uniqueness: true
  validates :location, presence: true, uniqueness: true
  validates :business_start_hours, presence: true
  validates :business_finish_hours, presence: true
  validates :holiday, presence: true
  validates :image, presence: true

  def self.looks(search, word)
    @shop=Shop.where("name LIKE?", "%#{word}%")
  end
end

app/models/shop_comment.rb
class ShopComment < ApplicationRecord
  belongs_to :user
  belongs_to :shop

  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shops
  has_many :shop_comments, dependent: :destroy
  has_many :favorite_shops, dependent: :destroy
  has_many :reviews, dependent: :destroy

  has_one_attached :image

  validates :name, presence: true
  validates :kana, presence: true
  validates :email, presence: true, uniqueness: true
  validates :image, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_user!
  def index
  end

  def create
  end

  def destroy
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @shops=Shop.all
  end

  def show
    @shop=Shop.find(params[:id])
    @user=@shop.user
  end

  def edit
    @shop=Shop.find(params[:id])
  end

  def update
    shop=Shop.find(params[:id])
    shop.update(admin_edit_shop_params)
    redirect_to admin_shop_path(shop.id)
  end

  private

  def admin_edit_shop_params
    params.require(:shop).permit(:name, :location, :genre_id, :business_start_hours, :business_finish_hours, :holiday, :image)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users=User.all
  end

  def show
    @user=User.find(params[:id])
     @comments=@user.shop_comments
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    user=User.find(params[:id])
    user.update(admin_user_edit_params)
    redirect_to admin_user_path(user)
  end

  def confirm_withdraw
    @user=User.find(params[:id])
  end

  def withdraw
    user=User.find(params[:id])

    user.update(status: false)
    flash[:admin_withdraw]="強制退会処理完了"
    redirect_to admin_users_path
  end

  private

  def admin_user_edit_params
    params.require(:user).permit(:name, :kana, :email, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/shop_comments_helper.rb
module Admin::ShopCommentsHelper
end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/create.html.erb
<h1>Admin::Genres#create</h1>
<p>Find me in app/views/admin/genres/create.html.erb</p>

app/views/admin/genres/destroy.html.erb
<h1>Admin::Genres#destroy</h1>
<p>Find me in app/views/admin/genres/destroy.html.erb</p>

app/views/admin/genres/index.html.erb
<h1>Admin::Genres#index</h1>
<p>Find me in app/views/admin/genres/index.html.erb</p>

app/views/admin/shops/edit.html.erb
<h2 class="admin-shop-edit-title">店舗情報編集</h2>

<%= form_with model: @shop, url: admin_shop_path do |f| %>
<table class="admin-edit-shop-table">
  <tr>
    <td><%= f.label :name, "店名" %></td>
    <td><%= f.text_field :name, class:"admin-edit-shop-form" %></td>
  </tr>
  <tr>
    <td><%= f.label :location, "所在地" %></td>
    <td><%= f.text_field :location, class:"admin-edit-shop-form" %></td>
  </tr>
  <tr>
    <td><%= f.label :genre_id, "ジャンル" %></td>
    <td><%= f.collection_select :genre_id, Genre.all, :id, :name, {include_blank: "--選択してください--"} %></td>
  </tr>
  <tr>
    <td><%= f.label :business_start_hours, "営業開始時間" %></td>
    <td><%= f.time_select :business_start_hours %></td>
  </tr>
  <tr>
    <td><%= f.label :business_finish_hours, "営業終了時間" %></td>
    <td><%= f.time_select :business_finish_hours %></td>
  </tr>
  <tr>
    <td><%= f.label :holiday, "休業日" %></td>
    <td><%= f.select :holiday, ["月曜日", "火曜日", "水曜日", "木曜日", "金曜日", "土曜日", "日曜日"], {include_blank: "--選択してください--"} %></td>
  </tr>
  <tr>
    <td><%= f.label :image, "店舗画像" %></td>
    <td><%= f.file_field :image %></td>
  </tr>
</table>

<%= f.submit "更新", class:"admin-shop-edit-button" %>
<% end %>

app/views/admin/shops/index.html.erb
<h2 class="index-shop-title">店舗一覧</h2>



<% @shops.each do |shop| %>
  <div class="index-shop-card">
   <div class="index-shop-image">
    <%= image_tag shop.image, class: "index-image" %>
   </div>
   <%#店舗情報表示部%>
   <table class="index-shop-info-table">
    <tr>
     <td>店名</td>
     <td><%= shop.name %></td>
    </tr>
    <tr>
     <td>所在地</td>
     <td><%= shop.location %></td>
    </tr>
    <tr>
     <td>ジャンル</td>
     <td><%= shop.genre.name %></td>
    </tr>
    <tr>
     <td>営業時間</td>
     <td><%= shop.business_start_hours.strftime("%H:%M") %>~<%= shop.business_finish_hours.strftime("%H:%M") %></td>
    </tr>
   </table>
   <%#店舗評価表示部%>
   <table class="index-shop-rate-table">
    <tr>
     <td>お店の雰囲気</td>
     <td>
      <div id="average-raty-atmosphere-<%= shop.id %>"></div>
      <script>
       let elem_atmosphere_<%= shop.id %> = document.querySelector('#average-raty-atmosphere-<%= shop.id %>');
       let opt_atmosphere_<%= shop.id %> = {
         size: 36,
         starOff: "<%= asset_path("star-off.png") %>",
         starOn: "<%= asset_path("star-on.png") %>",
         starHalf: "<%= asset_path("star-half.png") %>",
         half: true,
         score: <%= shop.reviews.average(:atmosphere_rate).to_f.round(1) %>,
         readOnly: true,
       };
       raty(elem_atmosphere_<%= shop.id %>,opt_atmosphere_<%= shop.id %>);
      </script>
     </td>
    </tr>
    <tr>
     <td>接客</td>
     <td>
      <div id="average-raty-servise-<%= shop.id %>"></div>
      <script>
       let elem_servise_<%= shop.id %> = document.querySelector('#average-raty-servise-<%= shop.id %>');
       let opt_servise_<%= shop.id %> = {
         size: 36,
         starOff: "<%= asset_path("star-off.png") %>",
         starOn: "<%= asset_path("star-on.png") %>",
         starHalf: "<%= asset_path("star-half.png") %>",
         half: true,
         score: <%= shop.reviews.average(:servise_rate).to_f.round(1) %>,
         readOnly: true,
       };
       raty(elem_servise_<%= shop.id %>,opt_servise_<%= shop.id %>);
      </script>
     </td>
    </tr>
    <tr>
     <td>味</td>
     <td>
      <div id="average-raty-taste-<%= shop.id %>"></div>
      <script>
       let elem_taste_<%= shop.id %> = document.querySelector('#average-raty-taste-<%= shop.id %>');
       let opt_taste_<%= shop.id %> = {
         size: 36,
         starOff: "<%= asset_path("star-off.png") %>",
         starOn: "<%= asset_path("star-on.png") %>",
         starHalf: "<%= asset_path("star-half.png") %>",
         half: true,
         score: <%= shop.reviews.average(:taste_rate).to_f.round(1) %>,
         readOnly: true,
       };
       raty(elem_taste_<%= shop.id %>,opt_taste_<%= shop.id %>);
      </script>
     </td>
    </tr>
    <tr>
     <td>混雑度</td>
     <td>
      <div id="average-raty-congestion-<%= shop.id %>"></div>
      <script>
       let elem_congestion_<%= shop.id %> = document.querySelector('#average-raty-congestion-<%= shop.id %>');
       let opt_congestion_<%= shop.id %> = {
         size: 36,
         starOff: "<%= asset_path("star-off.png") %>",
         starOn: "<%= asset_path("star-on.png") %>",
         starHalf: "<%= asset_path("star-half.png") %>",
         half: true,
         score: <%= shop.reviews.average(:congestion_rate).to_f.round(1) %>,
         readOnly: true,
       };
       raty(elem_congestion_<%= shop.id %>,opt_congestion_<%= shop.id %>);
      </script>
     </td>
    </tr>
   </table>
   <%#ボタン%>
   <div class="index-shop-button">
     <%= link_to "店舗詳細", admin_shop_path(shop.id), data: {"turbolinks" => false}, class:"index-shop-link-button-guest" %>
   </div>
  </div>
<% end %>

app/views/admin/shops/show.html.erb
<h2 class="show-shop-title">店舗詳細</h2>

  <div class="show-shop-card">
   <div class="show-shop-image">
    <%= image_tag @shop.image, class: "show-image" %>
   </div>
   <%#店舗情報表示部%>
   <table class="show-shop-info-table">
    <tr>
     <td>店名</td>
     <td><%= @shop.name %></td>
    </tr>
    <tr>
     <td>所在地</td>
     <td><%= @shop.location %></td>
    </tr>
    <tr>
     <td>ジャンル</td>
     <td><%= @shop.genre.name %></td>
    </tr>
    <tr>
     <td>営業時間</td>
     <td><%= @shop.business_start_hours.strftime("%H:%M") %>~<%= @shop.business_finish_hours.strftime("%H:%M") %></td>
    </tr>
   </table>
   <%#店舗評価表示部%>
   <table class="show-shop-rate-table">
    <tr>
     <td>お店の雰囲気</td>
     <td>
      <div id="average-raty-atmosphere-<%= @shop.id %>"></div>
      <script>
       let elem_atmosphere_<%= @shop.id %> = document.querySelector('#average-raty-atmosphere-<%= @shop.id %>');
       let opt_atmosphere_<%= @shop.id %> = {
         size: 36,
         starOff: "<%= asset_path("star-off.png") %>",
         starOn: "<%= asset_path("star-on.png") %>",
         starHalf: "<%= asset_path("star-half.png") %>",
         half: true,
         score: <%= @shop.reviews.average(:atmosphere_rate).to_f.round(1) %>,
         readOnly: true,
       };
       raty(elem_atmosphere_<%= @shop.id %>,opt_atmosphere_<%= @shop.id %>);
      </script>
     </td>
    </tr>
    <tr>
     <td>接客</td>
     <td>
      <div id="average-raty-servise-<%= @shop.id %>"></div>
      <script>
       let elem_servise_<%= @shop.id %> = document.querySelector('#average-raty-servise-<%= @shop.id %>');
       let opt_servise_<%= @shop.id %> = {
         size: 36,
         starOff: "<%= asset_path("star-off.png") %>",
         starOn: "<%= asset_path("star-on.png") %>",
         starHalf: "<%= asset_path("star-half.png") %>",
         half: true,
         score: <%= @shop.reviews.average(:servise_rate).to_f.round(1) %>,
         readOnly: true,
       };
       raty(elem_servise_<%= @shop.id %>,opt_servise_<%= @shop.id %>);
      </script>
     </td>
    </tr>
    <tr>
     <td>味</td>
     <td>
      <div id="average-raty-taste-<%= @shop.id %>"></div>
      <script>
       let elem_taste_<%= @shop.id %> = document.querySelector('#average-raty-taste-<%= @shop.id %>');
       let opt_taste_<%= @shop.id %> = {
         size: 36,
         starOff: "<%= asset_path("star-off.png") %>",
         starOn: "<%= asset_path("star-on.png") %>",
         starHalf: "<%= asset_path("star-half.png") %>",
         half: true,
         score: <%= @shop.reviews.average(:taste_rate).to_f.round(1) %>,
         readOnly: true,
       };
       raty(elem_taste_<%= @shop.id %>,opt_taste_<%= @shop.id %>);
      </script>
     </td>
    </tr>
    <tr>
     <td>混雑度</td>
     <td>
      <div id="average-raty-congestion-<%= @shop.id %>"></div>
      <script>
       let elem_congestion_<%= @shop.id %> = document.querySelector('#average-raty-congestion-<%= @shop.id %>');
       let opt_congestion_<%= @shop.id %> = {
         size: 36,
         starOff: "<%= asset_path("star-off.png") %>",
         starOn: "<%= asset_path("star-on.png") %>",
         starHalf: "<%= asset_path("star-half.png") %>",
         half: true,
         score: <%= @shop.reviews.average(:congestion_rate).to_f.round(1) %>,
         readOnly: true,
       };
       raty(elem_congestion_<%= @shop.id %>,opt_congestion_<%= @shop.id %>);
      </script>
     </td>
    </tr>
   </table>

   <div class="admin-show-shop-edit">
    <%= link_to "編集する", edit_admin_shop_path(@shop.id), class:"admin-show-shop-edit-link" %>
   </div>
  </div>

  <h2 class="admin-show-shop-post-user-title">投稿者</h2>

  <div class="admin-show-shop-post-user-card">
    <table class="admin-show-shop-post-user-table">
      <thead class="admin-show-shop-post-user-table-thead">
       <tr>
        <th>プロフィール画像</th>
        <th>id</th>
        <th>名前</th>
        <th>フリガナ</th>
        <th>Eメールアドレス</th>
       </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= image_tag @user.image, size: "80x100" %></td>
          <td><%= @user.id %></td>
          <td><%= @user.name %></td>
          <td><%= @user.kana %></td>
          <td><%= @user.email %></td>
        </tr>
      </tbody>
    </table>
   <div class="admin-show-shop-post-user-button">
    <%= link_to "会員詳細", admin_user_path(@user.id), class:"admin-show-shop-post-user-show-link" %>
    <%= link_to "編集する", edit_admin_user_path(@user.id), class:"admin-show-shop-post-user-edit-link" %>
   </div>
  </div>

<%= link_to "店舗一覧へ戻る", admin_shops_path, data: {"turbolinks" => false}, class:"show-shop-link-button" %>

app/views/admin/shops/update.html.erb
<h1>Admin::Shops#update</h1>
<p>Find me in app/views/admin/shops/update.html.erb</p>

app/views/admin/users/confirm_withdraw.html.erb
<div class="user-withdraw-box">

  <h2 class="user-withdraw-title">会員退会確認画面</h2>

  <div class="user-withdraw-select">
    <h2>この会員を強制退会させますか？</h2>
  　<%= link_to "キャンセル", admin_user_path(@user.id), class:"user-withdraw-cancel-button" %>
  　<%= link_to "強制退会", withdraw_admin_user_path(@user.id), method: :patch, class:"user-withdraw-button" %>
  </div>
</div>

app/views/admin/users/edit.html.erb
<h2 class="edit-user-title">会員情報編集</h2>

<%#会員情報編集フォーム%>
<% if @user.status==true %>
<%= form_with model: @user, url: admin_user_path do |f| %>
<table class="edit-user-table">
  <tr>
    <td><%= f.label :name, "名前" %></td>
    <td><%= f.text_field :name, size: 25 %></td>
  </tr>
  <tr>
    <td><%= f.label :kana, "フリガナ" %></td>
    <td><%= f.text_field :kana, size: 25 %></td>
  </tr>
  <tr>
    <td><%= f.label :email, "Eメールアドレス" %></td>
    <td><%= f.text_field :email, size: 25 %></td>
  </tr>
  <tr>
    <td><%= f.label :image, "プロフィール画像(任意)" %></td>
    <td><%= f.file_field :image %></td>
  </tr>
</table>
  <%= f.submit "変更", class:"edit-user-button" %>
<% end %>
<% else %>
<div class="admin-edit-user-withdraw-message">
  <h1 class="admin-edit-user-withdraw-text">この会員は退会済です。</h1>
  <%= link_to "会員一覧に戻る", admin_shops_path, class:"admin-edit-user-index-link-button" %>
</div>
<% end %>

<% if @user.status==true %>
 <%= link_to "強制退会", withdraw_admin_user_path(@user.id), class:"edit-user-withdraw-link-button" %>
<% end %>

app/views/admin/users/index.html.erb
<h2 class="admin-index-user-title">会員一覧</h2>

<%#強制退会フラッシュメッセージ%>
<div class="admin-withdraw-flash-message">
  <%= flash[:admin_withdraw] %>
</div>

<% @users.each do |user| %>
 <div class="admin-index-user-card">
 <table class="admin-index-user-table">
  <% if user.status==true %>
      <thead class="admin-index-user-table-thead">
       <tr>
        <th>プロフィール画像</th>
        <th>id</th>
        <th>名前</th>
        <th>フリガナ</th>
        <th>Eメールアドレス</th>
        <th></th>
       </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= image_tag user.image, size: "80x100" %></td>
          <td><%= user.id %></td>
          <td><%= user.name %></td>
          <td><%= user.kana %></td>
          <td><%= user.email %></td>
          <td>登録中</td>
        </tr>
      </tbody>
  <% else %>
      <thead>
        <th>プロフィール画像</th>
        <th>id</th>
        <th>名前</th>
        <th>フリガナ</th>
        <th>Eメールアドレス</th>
        <th></th>
      </thead>
      <tbody>
        <tr>
          <td><%= image_tag user.image, size: "80x100" %></td>
          <td><%= user.id %></td>
          <td><%= user.name %></td>
          <td><%= user.kana %></td>
          <td><%= user.email %></td>
          <td>
            <span class="admin-index-user-status">
             <p>退会済</p>
            </span>
          </td>
        </tr>
      </tbody>
  <% end %>
 </table>
   <div class="admin-index-user-button">
    <%= link_to "編集する", edit_admin_user_path(user.id), class:"admin-index-user-edit-link" %>
    <%= link_to "会員詳細", admin_user_path(user.id), class:"admin-index-user-show-link" %>
   </div>
  </div>
<% end %>

app/views/admin/users/show.html.erb
<h2 class="admin-show-user-title">会員情報詳細</h2>

<div class="admin-show-user-card">
    <table class="admin-show-user-table">
      <thead class="admin-show-user-table-thead">
       <tr>
        <th>プロフィール画像</th>
        <th>id</th>
        <th>名前</th>
        <th>フリガナ</th>
        <th>Eメールアドレス</th>
        <th></th>
       </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= image_tag @user.image, size: "80x100" %></td>
          <td><%= @user.id %></td>
          <td><%= @user.name %></td>
          <td><%= @user.kana %></td>
          <td><%= @user.email %></td>
          <td>
            <span class="admin-index-user-status">
              <% if @user.status==true %>
               <p>登録中</p>
              <% else %>
               <P>退会済</P>
              <% end %>
              </span>
          </td>
        </tr>
      </tbody>
    </table>
   <div class="admin-show-user-button">
    <%= link_to "編集する", edit_admin_user_path(@user.id), class:"admin-show-user-edit-link" %>
   </div>
  </div>

  <div class="admin-show-user-comments-title">
    <h2><%= @user.name %>の投稿コメント一覧</h2>
  </div>

  <div class="admin-show-user-comments-card">
  <table class="admin-show-user-comments-table">
    <thead>
      <tr>
        <th>投稿日</th>
        <th>投稿内容</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.created_at.strftime("%Y-%m-%d") %></td>
        <td><%= comment.comment %></td>
        <td>
          <%= link_to "削除する", admin_shop_comment_path(comment.id), method: :delete, class:"admin-show-user-comments-delete-button" %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  </div>

app/views/admin/users/update.html.erb
<h1>Admin::Users#update</h1>
<p>Find me in app/views/admin/users/update.html.erb</p>

app/views/admin/users/withdraw.html.erb
<h1>Admin::Users#withdraw</h1>
<p>Find me in app/views/admin/users/withdraw.html.erb</p>