config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'maps/index'
  end
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
#会員側ルーティング
   scope module: :public do
    root to: "homes#top"
    resources :shops do
     collection do
       get "/favorites" => "shops#favorite"
     end
      resource :favorite_shops, only: [:create, :destroy]
      resource :reviews, only: [:create, :update]
      resources :shop_comments, only: [:create, :destroy]
      resources :maps, only: [:index]
    end
    get "users/my_page" => "users#show"
    get "users/information/edit" => "users#edit"
    patch "users/information" => "users#update"
    put "users/information" => "users#update"
    get "users/shops" =>"users#index"
    get "users/withdraw" => "users#confirm_withdraw"
    patch "users/withdraw" => "users#withdraw"
    get "users/comments" => "users#comments"
    delete "users/comments" => "users#comment_destroy"
    resources :genres, only: [:new, :create, :show]
    get "genre_search" => "searches#genre_search"
    get "search" => "searches#name_search"
    get "rank" => "ranks#rank"
  end
#管理者側ルーティング
  namespace :admin do
    get "" => "homes#top"
    resources :users, :except => :destroy do
      member do
        get "/withdraw" => "users#confirm_withdraw"
        patch "/withdraw" => "users#withdraw"
      end
    end
    resources :genres, only: [:index, :create, :destroy]
    resources :shops, :except => [:create, :destroy]
    resources :shop_comments, only: [:index, :show, :destroy]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :shops
end

app/models/favorite_shop.rb
class FavoriteShop < ApplicationRecord
  belongs_to :user
  belongs_to :shop

  validates_uniqueness_of :shop_id, scope: :user_id
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :shops, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :shop

end

app/models/shop.rb
class Shop < ApplicationRecord
  geocoded_by :location
  after_validation :geocode

  belongs_to :user
  belongs_to :genre
  has_many :favorite_shops, dependent: :destroy
  has_many :shop_comments, dependent: :destroy
  has_many :reviews, dependent: :destroy

  has_one_attached :image

  validates :name, presence: true, uniqueness: true
  validates :location, presence: true, uniqueness: true
  validates :business_start_hours, presence: true
  validates :business_finish_hours, presence: true
  validates :holiday, presence: true
  validates :image, presence: true

  def self.looks(search, word)
    @shop=Shop.where("name LIKE?", "%#{word}%")
  end
end

app/models/shop_comment.rb
class ShopComment < ApplicationRecord
  belongs_to :user
  belongs_to :shop

  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shops
  has_many :shop_comments, dependent: :destroy
  has_many :favorite_shops, dependent: :destroy
  has_many :reviews, dependent: :destroy

  has_one_attached :image

  validates :name, presence: true
  validates :kana, presence: true
  validates :email, presence: true, uniqueness: true
  validates :image, presence: true
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @shops=Shop.all
  end

  def show
    @shop=Shop.find(params[:id])
    @user=@shop.user
  end

  def edit
    @shop=Shop.find(params[:id])
  end

  def update
    shop=Shop.find(params[:id])
    shop.update(admin_edit_shop_params)
    redirect_to admin_shop_path(shop.id)
  end

  private

  def admin_edit_shop_params
    params.require(:shop).permit(:name, :location, :genre_id, :business_start_hours, :business_finish_hours, :holiday, :image)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users=User.all
  end

  def show
    @user=User.find(params[:id])
     @comments=@user.shop_comments
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    user=User.find(params[:id])
    user.update(admin_user_edit_params)
    redirect_to admin_user_path(user)
  end

  def confirm_withdraw
    @user=User.find(params[:id])
  end

  def withdraw
    user=User.find(params[:id])

    user.update(status: false)
    flash[:admin_withdraw]="強制退会処理完了"
    redirect_to admin_users_path
  end

  private

  def admin_user_edit_params
    params.require(:user).permit(:name, :kana, :email, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/shop_comments_helper.rb
module Admin::ShopCommentsHelper
end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_error.html.erb
<% if obj.errors.any? %>
 <div class="alert">
  <h2><%= obj.errors.count %>個の入力エラー</h2>
  <% obj.errors.full_messages.each do |message| %>
   <ul>
    <li><%= message %></li>
   </ul>
  <% end %>
 </div>
<% end %>

app/views/layouts/_header.html.erb
<%#ヘッダー部分%>
    <header>
     <%= link_to root_path, class: "logo-link" do %>
      <h2 class="logo">ラーメンマッピング</h2>
     <% end %>
     <%#ログインステータス%>
     <% if admin_signed_in? %>
      <h4 class="admin-login-status-text">管理者ログイン中</h4>
      <h5 class="admin-login-flash-message-text"><%= flash[:success] %></h5>
     <% end %>

     <% if user_signed_in? %>
      <h4 class="login-status-text">ログイン中：<%= current_user.name %></p>
      <h5 class="flash-message-text"><%= flash[:success] %></h5>
     <% end %>


     <%#メニューバー部分%>
     <nav>
       <ul>
        <% if admin_signed_in? %>
        <li>
          <%= link_to "会員一覧", admin_users_path, class: "list-box" %>
        </li>
        <li>
          <%= link_to "店舗一覧", admin_shops_path, data: {"turbolinks" => false}, class:"list-box" %>
        </li>
        <li>
          <%= link_to "コメント一覧", admin_shop_comments_path, class:"list-box" %>
        </li>
        <li>
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"list-box" %>
        </li>
        <% elsif user_signed_in? %>
        <li>
          <%= link_to "ジャンル登録", new_genre_path, class:"list-box" %>
        </li>
        <li>
          <%= link_to "店舗登録", new_shop_path, class:"list-box" %>
        </li>
        <li>
          <%= link_to "店舗一覧", shops_path, data: {"turbolinks" => false}, class:"list-box" %>
        </li>
        <li>
          <%= link_to "会員情報", users_my_page_path, class:"list-box" %>
        </li>
        <li>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"list-box" %>
        </li>
        <% end %>
       </ul>
       <%= render "public/searches/name-search" %>
     </nav>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RamenMapping</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="//code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css"/>
    <script src="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%#ヘッダー部分%>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>